"""Downloadable prompt that lets any AI assistant map a trial balance to the CIT codes.

The prompt is built from the app's own chart of codes (data/chart_of_accounts.json) and keyword rules
(engine/code_suggest.py), so it always matches the version of the app that produced it.
The user uploads the prompt (.md) together with the TB (Excel) to an AI assistant and gets back the same TB
with a "CIT code", an "AI statement line (check)", an "AI confidence" and a "Comments" column — a file the
app reads directly on 1 · Trial Balance.
"""
from __future__ import annotations

from datetime import date

import pandas as pd

from engine import VERSION
from engine.code_suggest import keyword_hints, normal_side

FILE_NAME = "CIT_code_mapping_AI_prompt.md"
COMPUTED = {"BS 05.08": "profit or loss of the year", "BS 08.02.01": "income-tax provision of the year",
            "PL CIT": "income-tax charge of the year"}

EXAMPLES = [  # (account, debit, credit, code, confidence, comment)
    ("BK OF KIGALI CURRENT ACC", 12_500_000, 0, "BS 03.01.03.02", "High", ""),
    ("Office rent", 6_000_000, 0, "PL 04.12", "High", ""),
    ("Acc. dep. motor vehicles", 0, 4_200_000, "BS 01.10", "High", ""),
    ("Dep. motor vehicles", 1_400_000, 0, "PL 05.01", "High", ""),
    ("Interest", 0, 350_000, "PL 08.01", "Medium",
     "Proposed PL 08.01 (credit balance = interest received). Alternative PL 07.01 if it is interest paid — please check."),
    ("Director - current account", 0, 9_000_000, "BS 06.02.04", "Medium",
     "Proposed BS 06.02.04 (amount owed to the director). Alternative BS 06.01.04 if the loan is secured — please check."),
    ("Suspense account", 150_000, 0, "BS 03.01.04", "Low",
     "Suspense / balancing account — should be cleared before the report. Temporarily BS 03.01.04; please investigate."),
    ("TOTAL", 30_000_000, 30_000_000, "", "", "Total line — not mapped (ignored by the app)."),
]


def _side_label(code: str) -> str:
    if code == "BS 05.07":
        return "Credit (debit if losses)"
    return "Debit" if normal_side(code) == "DR" else "Credit"


def build(catalogue: pd.DataFrame, computed: dict | None = None) -> str:
    """Markdown prompt. catalogue: DataFrame code/statement/section/group/line/note (state.code_catalogue())."""
    hints = keyword_hints()
    computed = computed or COMPUTED
    L: list[str] = []
    a = L.append
    a(f"# Prompt — map a trial balance to the Rwanda CIT codes")
    a("")
    a(f"*Generated by FINDAP Annual Report Generator {VERSION} on {date.today():%d %B %Y}. "
      f"The list of codes below is the one used by the app — do not use any other list.*")
    a("")
    a("> **How to use this file (for the person, not for the AI):** open your AI assistant, attach **your trial "
      "balance (Excel)** and **this file**, and write: *\"Follow the instructions in the prompt file and map my trial "
      "balance.\"* Then upload the file you get back on **1 · Trial Balance → Upload TB** in the app, and review the "
      "lines marked Medium or Low (their comments explain the doubt).")
    a(">")
    a("> **Confidentiality:** your trial balance will be sent to the AI provider you choose. Check that your firm and "
      "your client allow it. You may remove amounts you consider sensitive — but keep at least the sign "
      "(debit or credit) of each balance, it helps the mapping.")
    a("")
    a("---")
    a("")
    a("## 1. Your role and task")
    a("")
    a("You are a chartered accountant experienced with Rwandan companies, IFRS for SMEs and the Rwanda Revenue "
      "Authority (RRA) corporate income tax (CIT) declaration. The user attached a **trial balance** (Excel or CSV). "
      "For **every account line**, choose the **one CIT code** from the list in section 5 that best describes the "
      "account, using its name (English, French or Kinyarwanda, abbreviations, typos) **and** the direction of its "
      "balance (debit or credit).")
    a("")
    a("## 2. Rules")
    a("")
    rules = [
        "Use **only** codes from section 5, written exactly as shown (e.g. `PL 04.12`, `BS 03.01.03.02`): `BS` or `PL`, a "
        "space, then every level on **2 digits**. Never invent a code, and never use the old one-digit codes (e.g. "
        "`BS 1.09`) even if the TB already contains them — replace them and say so in the comment.",
        "Some codes have one more level (e.g. `PL 05.08.02` Fines and penalties, `BS 03.01.04.01` VAT receivables): they are "
        "detailed lines of the RRA line above them. Use them whenever they fit — they matter for the tax computation.",
        "Computers, laptops, printers, servers and accessories go to `BS 01.07` (IT equipment), not to other assets.",
        "**Never change** the account names, the amounts, the years, the order of the lines or the number of lines. "
        "Do not merge, split, sort or delete lines.",
        "A line that already has a valid code from section 5: keep it, unless it is clearly wrong — then propose the "
        "right one and explain in the comment. A code not in section 5: replace it and say so in the comment.",
        "Use the **balance direction** as a strong hint (column *Usual balance* in section 5). Examples: a bank account "
        "with a credit balance is an overdraft (`BS 08.01.04`); \"depreciation\" with a credit balance is accumulated "
        "depreciation (`BS 01.10`), with a debit balance it is the charge of the year (`PL 05.01`); \"interest\" with a "
        "credit balance is income (`PL 08.01`), with a debit balance an expense (`PL 07.01`); VAT or WHT with a credit "
        "balance is a liability (`BS 08.01.06` or `BS 07.02`), with a debit balance a receivable (`BS 03.01.04.01` / `BS 03.01.04.02`); "
        "a customer with a credit balance or a supplier with a debit balance is an advance — say so in the comment.",
        "Accumulated depreciation / amortisation of **all** asset classes goes to `BS 01.10` (one line per asset class "
        "is fine). The depreciation charge of the year goes to `PL 05.01` (`PL 02.04.06` only for factory depreciation "
        "inside cost of goods sold).",
        "Retained earnings `BS 05.07` = the balance at the **start** of the year (profit or loss brought forward).",
        "Stock: opening stock in the P&L → `PL 02.01.xx`; closing stock in the P&L → `PL 02.05.xx`; stock on the balance "
        "sheet → `BS 03.01.01.xx`.",
        "Codes computed by the app, **not** taken from the trial balance: "
        + "; ".join(f"`{c}` ({v})" for c, v in computed.items())
        + ". If the TB contains the profit of the year or the income-tax charge of the year, leave the code empty and "
          "comment: *\"Computed by the app — remove this line from the TB.\"*",
        "Total, sub-total, heading and blank lines: leave the code empty and comment *\"Total line — not mapped\"* "
        "(the app ignores them).",
        "Suspense, balancing, \"to be allocated\" or clearing accounts: propose the most likely code, confidence "
        "**Low**, and say in the comment that the account should be cleared before the report.",
        "When two codes are possible (e.g. a generic \"Office expenses\"), pick the most likely one and give the "
        "alternative in the comment. **Do not ask the user questions** — decide, and explain doubts in the comments.",
    ]
    for i, r in enumerate(rules, 1):
        a(f"{i}. {r}")
    a("")
    a("## 3. Confidence and comments")
    a("")
    a("| Confidence | When | Comment |")
    a("|---|---|---|")
    a("| **High** | name and balance direction clearly point to one code | leave empty (or keep the original comment) |")
    a("| **Medium** | likely code, but another one is possible | *\"Proposed X (reason). Alternative Y if … — please check.\"* |")
    a("| **Low** | unclear name, unusual balance, suspense account | *\"Proposed X (reason). Please confirm with the accountant.\"* |")
    a("")
    a("If the TB already has a comments column, **keep its text** and add yours after it, separated by ` | `.")
    a("")
    a("## 4. What to return")
    a("")
    a("Return **the same trial balance** as an **Excel file (.xlsx)** named like the original with `_mapped` added "
      "(e.g. `TB_2025_mapped.xlsx`):")
    a("")
    a("- the same sheet, the same title rows, the same header row and the same columns, in the same order;")
    a("- a column titled exactly **`CIT code`** — fill it if it exists; otherwise insert it **just before the account "
      "name column**;")
    a("- three columns added at the end, titled exactly **`AI statement line (check)`** (the statement line of the "
      "code, from section 5), **`AI confidence`** (High / Medium / Low) and **`Comments`** (use the existing comments "
      "column if there is one);")
    a("- keep the year in the amount column titles (e.g. *Debit 2025*, *Credit 2025*) exactly as in the original.")
    a("")
    a("**If you cannot create an Excel file**, return the full table as **CSV** in a code block (comma separator, "
      "amounts without thousands separators, header row first) so that the user can save it as `.csv`.")
    a("")
    a("After the file, write a **short summary**: number of lines mapped per confidence level, then a table of the "
      "Medium and Low lines (line number, account, proposed code, reason), and any line you left without a code.")
    a("")
    a("### Example (extract)")
    a("")
    a("| CIT code | Account name | Debit 2025 | Credit 2025 | AI statement line (check) | AI confidence | Comments |")
    a("|---|---|---:|---:|---|---|---|")
    cat = catalogue.set_index("code")
    for acc, dr, cr, code, conf, com in EXAMPLES:
        line = cat.at[code, "line"] if code in cat.index else ""
        a(f"| {code} | {acc} | {dr:,.0f} | {cr:,.0f} | {line} | {conf} | {com} |")
    a("")
    a("## 5. List of CIT codes (the only codes allowed)")
    a("")
    a("*Usual balance* is the normal side of the account in a trial balance. *Keywords* are examples of account "
      "names (English / French), not an exhaustive list.")
    for stmt in dict.fromkeys(catalogue["statement"]):
        a("")
        a(f"### {stmt}")
        a("")
        a("| CIT code | RRA Serial No | Section | Group | Statement line | Usual balance | Keywords (examples) |")
        a("|---|---|---|---|---|---|---|")
        for r in catalogue[catalogue["statement"] == stmt].itertuples():
            grp = r.group if r.group != r.section else ""
            ser = ".".join(str(int(x)) for x in r.code.split(" ")[1].split("."))
            a(f"| {r.code} | {ser} | {r.section} | {grp} | {r.line} | {_side_label(r.code)} | {hints.get(r.code, '')} |")
    a("")
    a("---")
    a("*End of prompt.*")
    return "\n".join(L) + "\n"


def build_bytes(catalogue: pd.DataFrame, computed: dict | None = None) -> bytes:
    return build(catalogue, computed).encode("utf-8")
